# import modules, classes and functions to create urls
from django.urls import path
from .views import ( share_file_view, sort_file_view , file_search_view, edit_permission_view, 
                    rename_file_view, recycle_file_view, sort_file_grid_view, file_search_grid_view,
                    folder_detail_view, multiple_file_upload_view, directory_upload_view, create_folder_view,
                    share_folder_view, rename_folder_view, edit_folder_permission_view, recycle_folder_view,
                    folder_search_view, folder_detail_grid_view, multiple_file_upload_grid_view, directory_upload_grid_view,
                    sort_folder_grid_view, folder_search_grid_view, shared_file_search_view, sort_shared_file_view,
                    sort_shared_file_grid_view, shared_file_search_grid_view, shared_folder_search_view, shared_folder_search_grid_view,
                    sort_shared_folder_grid_view, recycled_files_view, recycled_folders_view, restore_file_view, restore_folder_view,
                    delete_file_view, delete_folder_view, create_private_folder_view, private_folder_detail_view,
                    private_file_search_view, private_sort_file_view,
                    private_file_search_grid_view, sort_private_file_grid_view, multiple_private_file_upload_view, private_directory_upload_view,
                    private_folder_search_view, private_folder_detail_grid_view, multiple_private_file_upload_grid_view, private_directory_upload_grid_view,
                    sort_private_folder_grid_view, private_folder_search_grid_view, shared_with_view, delete_shared_user_view, show_statistics_view,
                    folder_delete_shared_user_view, folder_shared_with_view,
                     PublicFileUpdateView, PublicFileCreateView, PublicFileCreateGridView, PublicFolderCreateView,
                     PublicFolderCreateGridView, SharedFileCreateView, SharedFileCreateGridView, SharedFolderCreateView,
                     SharedFolderCreateGridView, PrivateFileCreateView, PrivateFileUpdateView, PrivateFileCreateGridView,PrivateFolderCreateView,
                     PrivateFolderCreateGridView, AnnouncementCreateView,
                     )



urlpatterns = [
    path('home/', PublicFileCreateView.as_view(), name='file_list'),
    path('create_folder/', create_folder_view, name='folder_create'),
    path('project_data/', show_statistics_view, name='project_data'),
    path('search_files/', file_search_view, name='file_search_list'),
    path('sort_files/', sort_file_view, name='sort_file_list'),
    path('share/', share_file_view, name='share_file'),
    path('rename_file/', rename_file_view, name='rename_file'),
    path('shared_with/', shared_with_view, name='shared_with'),
    path('delete_shared_user/', delete_shared_user_view, name='delete_shared_user'),
    path('updatepublicfile/<uuid:pk>', PublicFileUpdateView.as_view(), name='update_public_file'),
    path('edit_permission/', edit_permission_view, name='edit_file_permission'),
    path('recycle_file/', recycle_file_view, name='recycle_file'),
    path('home/grid/', PublicFileCreateGridView.as_view(), name='file_list_grid'),
    path('search_files/grid/', file_search_grid_view, name='file_search_grid'),
    path('sort_files/grid/', sort_file_grid_view, name='sort_file_grid'),
    path('public_folders/', PublicFolderCreateView.as_view(), name='folder_list'),
    path('search_folders/', folder_search_view, name='folder_search_list'),
    path('upload_multi_files/<uuid:pk>', multiple_file_upload_view, name='upload_multi_files'),
    path('upload_directory/<uuid:pk>', directory_upload_view, name='directory_upload'),
    path('share_folder/', share_folder_view, name='share_folder'),
    path('rename_folder/', rename_folder_view, name='rename_folder'),
    path('edit_folder_permission/', edit_folder_permission_view, name='edit_folder_permission'),
    path('recycle_folder/', recycle_folder_view, name='recycle_folder'),
    path('folder_shared_with/', folder_shared_with_view, name='folder_shared_with'),
    path('folder_delete_shared_user/', folder_delete_shared_user_view, name='folder_delete_shared_user'),
    path('public_folders/<uuid:pk>', folder_detail_view, name='folder_detail'),
    path('public_folders/grid/', PublicFolderCreateGridView.as_view(), name='folder_list_grid'),
    path('search_folders/grid/', folder_search_grid_view, name='folder_search_grid'),
    path('upload_multi_files/grid/<uuid:pk>', multiple_file_upload_grid_view, name='upload_multi_files_grid'),
    path('upload_directory/grid/<uuid:pk>', directory_upload_grid_view, name='directory_upload_grid'),
    path('sort_folders/grid/', sort_folder_grid_view, name='sort_folder_grid'),
    path('public_folders/grid/<uuid:pk>', folder_detail_grid_view, name='folder_detail_grid'),
    path('shared_files/', SharedFileCreateView.as_view(), name='file_shared'),
    path('search_files/shared/', shared_file_search_view, name='shared_file_search_list'),
    path('sort_shared_files/', sort_shared_file_view, name='sort_shared_file_list'),
    path('shared_files/grid/', SharedFileCreateGridView.as_view(), name='file_shared_grid'),
    path('search_files/shared/grid', shared_file_search_grid_view, name='shared_file_search_grid'),
    path('sort_shared_files/grid/', sort_shared_file_grid_view, name='sort_shared_file_grid'),
    path('shared_folders/', SharedFolderCreateView.as_view(), name='folder_shared'),
    path('search_folders/shared/', shared_folder_search_view, name='shared_folder_search_list'),
    path('shared_folders/grid/', SharedFolderCreateGridView.as_view(), name='folder_shared_grid'),
    path('search_folders/shared/grid/', shared_folder_search_grid_view, name='shared_folder_search_grid'),
    path('sort_shared_folders/grid/', sort_shared_folder_grid_view, name='sort_shared_folder_grid'),
    path('recycled_files', recycled_files_view, name='recycled_files'),
    path('restore_file', restore_file_view, name='restore_file'),
    path('delete_file', delete_file_view, name='delete_file'),
    path('recycled_folders', recycled_folders_view, name='recycled_folders'),
    path('restore_folder', restore_folder_view, name='restore_folder'),
    path('delete_folder', delete_folder_view, name='delete_folder'),


    # private section
    path('private_files/', PrivateFileCreateView.as_view(), name='private_file_list'),
    path('create_private_folder/', create_private_folder_view, name='private_folder_create'),
    path('updateprivatefile/<uuid:pk>', PrivateFileUpdateView.as_view(), name='update_private_file'),
    path('search_private_files/', private_file_search_view, name='private_file_search_list'),
    path('sort_private_files/', private_sort_file_view, name='private_sort_file_list'),
    path('private_files/grid/', PrivateFileCreateGridView.as_view(), name='private_file_list_grid'),
    path('search_private_files/grid/', private_file_search_grid_view, name='private_file_search_grid'),
    path('sort_private_files/grid/', sort_private_file_grid_view, name='private_sort_file_grid'),
    path('upload_multi_private_files/<uuid:pk>', multiple_private_file_upload_view, name='private_upload_multi_files'),
    path('upload_private_directory/<uuid:pk>', private_directory_upload_view, name='private_directory_upload'),
    path('private_folders/', PrivateFolderCreateView.as_view(), name='private_folder_list'),
    path('private_folders/<uuid:pk>', private_folder_detail_view, name='private_folder_detail'),
    path('search_private_folders/', private_folder_search_view, name='private_folder_search_list'),
    path('private_folders/grid/', PrivateFolderCreateGridView.as_view(), name='private_folder_list_grid'),
    path('upload_multi_private_files/grid/<uuid:pk>', multiple_private_file_upload_grid_view, name='private_upload_multi_files_grid'),
    path('upload_private_directory/grid/<uuid:pk>', private_directory_upload_grid_view, name='private_directory_upload_grid'),
    path('private_folders/grid/<uuid:pk>', private_folder_detail_grid_view, name='private_folder_detail_grid'),
    path('search_private_folders/grid/', private_folder_search_grid_view, name='private_folder_search_grid'),
    path('sort_private_folders/grid/', sort_private_folder_grid_view, name='private_sort_folder_grid'),
    # path('shared_private_files/', SharedPrivateFileCreateView.as_view(), name='private_file_shared'),
    # path('search_private_files/shared/', shared_private_file_search_view, name='private_shared_file_search_list'),
    # path('sort_shared_private_files/', sort_shared_private_file_view, name='private_sort_shared_file_list'),
    # path('shared_private_files/grid/', SharedPrivateFileCreateGridView.as_view(), name='private_file_shared_grid'),
    # path('search_private_files/shared/grid', shared_private_file_search_grid_view, name='private_shared_file_search_grid'),
    # path('sort_shared_private_files/grid/', sort_shared_private_file_grid_view, name='private_sort_shared_file_grid'),
    # path('shared_private_folders/', SharedPrivateFolderCreateView.as_view(), name='private_folder_shared'),
    # path('search_private_folders/shared/', shared_private_folder_search_view, name='private_shared_folder_search_list'),
    # path('shared_private_folders/grid/', SharedPrivateFolderCreateGridView.as_view(), name='private_folder_shared_grid'),
    # path('search_private_folders/shared/grid/', shared_private_folder_search_grid_view, name='private_shared_folder_search_grid'),
    # path('sort_shared_private_folders/grid/', sort_shared_private_folder_grid_view, name='private_sort_shared_folder_grid'),

    # announcement
    path('announcement/', AnnouncementCreateView.as_view(), name='announcement'),
]

# sort_shared_private_file_view, shared_private_file_search_view,shared_private_file_search_grid_view, sort_shared_private_file_grid_view, shared_private_folder_search_grid_view, shared_private_folder_search_view,sort_shared_private_folder_grid_view,
#  SharedPrivateFileCreateView, SharedPrivateFileCreateGridView, SharedPrivateFolderCreateView,SharedPrivateFolderCreateGridView,