# Generated by Django 4.1.3 on 2022-11-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_custom_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_commenter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_content_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_contributor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_viewer',
        ),
    ]
