# Generated by Django 4.1.3 on 2022-11-06 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_is_commenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
