# Generated by Django 4.1.3 on 2022-11-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_change_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_change_requested',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
