# Generated by Django 4.1.7 on 2023-03-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0006_announcement'),
        ('notification', '0002_alter_notification_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='filesystem.announcement'),
        ),
    ]
