# Generated by Django 4.1.7 on 2023-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='old_file_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='old_folder_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
