# Generated by Django 4.1.7 on 2023-03-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_old_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='old_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='old_folder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
