# Generated by Django 4.1.7 on 2023-03-04 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filesystem.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.FileField(storage=filesystem.storage.Storage(), upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('permission_field', models.CharField(choices=[('View', 'View'), ('All', 'All')], default='All', max_length=10)),
                ('recycled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PublicFolders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('recycled', models.BooleanField(default=False)),
                ('permission_field', models.CharField(choices=[('View', 'View'), ('All', 'All')], default='All', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFolders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_field', models.CharField(choices=[('View', 'View'), ('All', 'All')], default='All', max_length=10)),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.publicfolders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_field', models.CharField(choices=[('View', 'View'), ('All', 'All')], default='All', max_length=10)),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.publicfiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publicfiles',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesystem.publicfolders'),
        ),
        migrations.AddField(
            model_name='publicfiles',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
