# Generated by Django 4.1.7 on 2023-03-06 12:26

from django.db import migrations, models
import filesystem.storage


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_alter_publicfiles_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfiles',
            name='filename',
            field=models.FileField(storage=filesystem.storage.Storage(), upload_to=''),
        ),
    ]
