# Generated by Django 4.1.7 on 2023-03-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0004_privatefiles_privatefolders_sharedprivatefolders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefolders',
            name='folder_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='publicfolders',
            name='folder_name',
            field=models.CharField(max_length=30),
        ),
    ]
