# Generated by Django 4.1.7 on 2023-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0005_alter_privatefolders_folder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.CharField(choices=[('Everyone', 'Everyone'), ('Admins only', 'Admins only')], default='Everyone', max_length=15)),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
