# Generated by Django 4.1.7 on 2023-03-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0006_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfiles',
            name='permission_field',
            field=models.CharField(choices=[('View', 'View'), ('All', 'All')], max_length=10),
        ),
    ]
