# Generated by Django 4.1.7 on 2023-03-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0007_alter_publicfiles_permission_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfiles',
            name='permission_field',
            field=models.CharField(choices=[('View', 'View'), ('All', 'All')], default='All', max_length=10),
        ),
    ]
