# Generated by Django 4.1.7 on 2023-03-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0010_alter_publicfiles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatefiles',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='privatefolders',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='publicfolders',
            options={'ordering': ['-date']},
        ),
    ]
