# Generated by Django 4.1.7 on 2023-03-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0011_alter_privatefiles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefolders',
            name='folder_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicfolders',
            name='folder_name',
            field=models.CharField(max_length=100),
        ),
    ]
