# Generated by Django 4.1.7 on 2023-03-15 17:01

from django.db import migrations, models
import filesystem.storage


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0012_alter_privatefolders_folder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefiles',
            name='filename',
            field=models.FileField(max_length=255, storage=filesystem.storage.Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicfiles',
            name='filename',
            field=models.FileField(max_length=255, storage=filesystem.storage.Storage(), upload_to=''),
        ),
    ]
