# Generated by Django 4.1.7 on 2023-03-15 19:02

from django.db import migrations, models
import filesystem.storage


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0013_alter_privatefiles_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefiles',
            name='filename',
            field=models.FileField(storage=filesystem.storage.Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicfiles',
            name='filename',
            field=models.FileField(storage=filesystem.storage.Storage(), upload_to=''),
        ),
    ]
